### PR TITLE
Added single_annotation_tool, basically the SLB AI Lab SRPC Version

### PR DESCRIPTION
**Pull request by Huang-Frederic**

### CODE REVIEW

**Review by franchesoni — CHANGES_REQUESTED** [review]
The changes now are in both the new folder and the root of the repo. Is it possible to you to keep the root as it was before and only add your new folder?
Also, the directory "exemple_images" should be called "example_images"

**Comment by Huang-Frederic** [comment]
Hey, Im very sorry for my mistake, after a small review from my side, I indeed overwritten your whole project and double pasted my code. I should have fixed this, let me know if there is more to do from my side !

**Review by franchesoni — APPROVED** [review]
good, isolated dir

**Comment by franchesoni** [comment]
thanks!

**Pull request merged**
